title:            Hafsah Shahzad's site
description:      Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //hafsahshahzad.github.io
#http://localhost:5000
#https://jponttuset.github.io
disqus_shortname: hafsahshahzad

# Owner/author information
owner:
  name:           Hafsah Shahzad
  avatar:         hafsah.jpg
  #bio:            I'm from a small town near Girona, Catalunya. Currently in Zürich, Switzerland. Passionate about computer vision, technology, running, and mountains.
  email:          hafsahshazad@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  #twitter: jponttuset
  linkedin: www.linkedin.com/in/hafsah-shahzad-8a692249
  google_scholar: https://scholar.google.com/citations?user=1oXnfh8AAAAJ&hl=en&oi=ao
  #google_plus: 113718226018314522413
  github: HafsahShahzad
# Analytics and webmaster tools stuff goes here
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
#links:
#  - title: Curriculum
#    url: /cv/
#  - title: Publications
#    url: /publications/
#  - title: Code
#    url: /code/
#  - title: Blog
#    url: /blog/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    UnitesStates
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

syntax_highlighter_opts:
  line_numbers:
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
